INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_TEST_MODULATION Test_Modulation)

FIND_PATH(
    TEST_MODULATION_INCLUDE_DIRS
    NAMES Test_Modulation/api.h
    HINTS $ENV{TEST_MODULATION_DIR}/include
        ${PC_TEST_MODULATION_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    TEST_MODULATION_LIBRARIES
    NAMES gnuradio-Test_Modulation
    HINTS $ENV{TEST_MODULATION_DIR}/lib
        ${PC_TEST_MODULATION_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TEST_MODULATION DEFAULT_MSG TEST_MODULATION_LIBRARIES TEST_MODULATION_INCLUDE_DIRS)
MARK_AS_ADVANCED(TEST_MODULATION_LIBRARIES TEST_MODULATION_INCLUDE_DIRS)

